[project]
name = "data-preparation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "kagglehub>=0.3.13",
    "pandas>=2.3.3",
    "scipy>=1.16.2",
]
